/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as PrivacyImport } from "./routes/privacy";
import { Route as LoginImport } from "./routes/login";
import { Route as AppImport } from "./routes/_app";
import { Route as AppIndexImport } from "./routes/_app.index";
import { Route as AppGamesImport } from "./routes/_app.games";
import { Route as AppGamesIndexImport } from "./routes/_app.games.index";
import { Route as AppGamesGameIdImport } from "./routes/_app.games.$gameId";
import { Route as AppTeamsTeamIdManageImport } from "./routes/_app.teams.$teamId.manage";
import { Route as AppTeamsTeamIdListsIndexImport } from "./routes/_app.teams.$teamId.lists.index";
import { Route as AppTeamsTeamIdListsListIdImport } from "./routes/_app.teams.$teamId.lists.$listId";

// Create/Update Routes

const PrivacyRoute = PrivacyImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any);

const AppRoute = AppImport.update({
  id: "/_app",
  getParentRoute: () => rootRoute,
} as any);

const AppIndexRoute = AppIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any);

const AppGamesRoute = AppGamesImport.update({
  id: "/games",
  path: "/games",
  getParentRoute: () => AppRoute,
} as any);

const AppGamesIndexRoute = AppGamesIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppGamesRoute,
} as any);

const AppGamesGameIdRoute = AppGamesGameIdImport.update({
  id: "/$gameId",
  path: "/$gameId",
  getParentRoute: () => AppGamesRoute,
} as any);

const AppTeamsTeamIdManageRoute = AppTeamsTeamIdManageImport.update({
  id: "/teams/$teamId/manage",
  path: "/teams/$teamId/manage",
  getParentRoute: () => AppRoute,
} as any);

const AppTeamsTeamIdListsIndexRoute = AppTeamsTeamIdListsIndexImport.update({
  id: "/teams/$teamId/lists/",
  path: "/teams/$teamId/lists/",
  getParentRoute: () => AppRoute,
} as any);

const AppTeamsTeamIdListsListIdRoute = AppTeamsTeamIdListsListIdImport.update({
  id: "/teams/$teamId/lists/$listId",
  path: "/teams/$teamId/lists/$listId",
  getParentRoute: () => AppRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AppImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    "/privacy": {
      id: "/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof PrivacyImport;
      parentRoute: typeof rootRoute;
    };
    "/_app/games": {
      id: "/_app/games";
      path: "/games";
      fullPath: "/games";
      preLoaderRoute: typeof AppGamesImport;
      parentRoute: typeof AppImport;
    };
    "/_app/": {
      id: "/_app/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AppIndexImport;
      parentRoute: typeof AppImport;
    };
    "/_app/games/$gameId": {
      id: "/_app/games/$gameId";
      path: "/$gameId";
      fullPath: "/games/$gameId";
      preLoaderRoute: typeof AppGamesGameIdImport;
      parentRoute: typeof AppGamesImport;
    };
    "/_app/games/": {
      id: "/_app/games/";
      path: "/";
      fullPath: "/games/";
      preLoaderRoute: typeof AppGamesIndexImport;
      parentRoute: typeof AppGamesImport;
    };
    "/_app/teams/$teamId/manage": {
      id: "/_app/teams/$teamId/manage";
      path: "/teams/$teamId/manage";
      fullPath: "/teams/$teamId/manage";
      preLoaderRoute: typeof AppTeamsTeamIdManageImport;
      parentRoute: typeof AppImport;
    };
    "/_app/teams/$teamId/lists/$listId": {
      id: "/_app/teams/$teamId/lists/$listId";
      path: "/teams/$teamId/lists/$listId";
      fullPath: "/teams/$teamId/lists/$listId";
      preLoaderRoute: typeof AppTeamsTeamIdListsListIdImport;
      parentRoute: typeof AppImport;
    };
    "/_app/teams/$teamId/lists/": {
      id: "/_app/teams/$teamId/lists/";
      path: "/teams/$teamId/lists";
      fullPath: "/teams/$teamId/lists";
      preLoaderRoute: typeof AppTeamsTeamIdListsIndexImport;
      parentRoute: typeof AppImport;
    };
  }
}

// Create and export the route tree

interface AppGamesRouteChildren {
  AppGamesGameIdRoute: typeof AppGamesGameIdRoute;
  AppGamesIndexRoute: typeof AppGamesIndexRoute;
}

const AppGamesRouteChildren: AppGamesRouteChildren = {
  AppGamesGameIdRoute: AppGamesGameIdRoute,
  AppGamesIndexRoute: AppGamesIndexRoute,
};

const AppGamesRouteWithChildren = AppGamesRoute._addFileChildren(AppGamesRouteChildren);

interface AppRouteChildren {
  AppGamesRoute: typeof AppGamesRouteWithChildren;
  AppIndexRoute: typeof AppIndexRoute;
  AppTeamsTeamIdManageRoute: typeof AppTeamsTeamIdManageRoute;
  AppTeamsTeamIdListsListIdRoute: typeof AppTeamsTeamIdListsListIdRoute;
  AppTeamsTeamIdListsIndexRoute: typeof AppTeamsTeamIdListsIndexRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppGamesRoute: AppGamesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppTeamsTeamIdManageRoute: AppTeamsTeamIdManageRoute,
  AppTeamsTeamIdListsListIdRoute: AppTeamsTeamIdListsListIdRoute,
  AppTeamsTeamIdListsIndexRoute: AppTeamsTeamIdListsIndexRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

export interface FileRoutesByFullPath {
  "": typeof AppRouteWithChildren;
  "/login": typeof LoginRoute;
  "/privacy": typeof PrivacyRoute;
  "/games": typeof AppGamesRouteWithChildren;
  "/": typeof AppIndexRoute;
  "/games/$gameId": typeof AppGamesGameIdRoute;
  "/games/": typeof AppGamesIndexRoute;
  "/teams/$teamId/manage": typeof AppTeamsTeamIdManageRoute;
  "/teams/$teamId/lists/$listId": typeof AppTeamsTeamIdListsListIdRoute;
  "/teams/$teamId/lists": typeof AppTeamsTeamIdListsIndexRoute;
}

export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/privacy": typeof PrivacyRoute;
  "/": typeof AppIndexRoute;
  "/games/$gameId": typeof AppGamesGameIdRoute;
  "/games": typeof AppGamesIndexRoute;
  "/teams/$teamId/manage": typeof AppTeamsTeamIdManageRoute;
  "/teams/$teamId/lists/$listId": typeof AppTeamsTeamIdListsListIdRoute;
  "/teams/$teamId/lists": typeof AppTeamsTeamIdListsIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/_app": typeof AppRouteWithChildren;
  "/login": typeof LoginRoute;
  "/privacy": typeof PrivacyRoute;
  "/_app/games": typeof AppGamesRouteWithChildren;
  "/_app/": typeof AppIndexRoute;
  "/_app/games/$gameId": typeof AppGamesGameIdRoute;
  "/_app/games/": typeof AppGamesIndexRoute;
  "/_app/teams/$teamId/manage": typeof AppTeamsTeamIdManageRoute;
  "/_app/teams/$teamId/lists/$listId": typeof AppTeamsTeamIdListsListIdRoute;
  "/_app/teams/$teamId/lists/": typeof AppTeamsTeamIdListsIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | ""
    | "/login"
    | "/privacy"
    | "/games"
    | "/"
    | "/games/$gameId"
    | "/games/"
    | "/teams/$teamId/manage"
    | "/teams/$teamId/lists/$listId"
    | "/teams/$teamId/lists";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/login"
    | "/privacy"
    | "/"
    | "/games/$gameId"
    | "/games"
    | "/teams/$teamId/manage"
    | "/teams/$teamId/lists/$listId"
    | "/teams/$teamId/lists";
  id:
    | "__root__"
    | "/_app"
    | "/login"
    | "/privacy"
    | "/_app/games"
    | "/_app/"
    | "/_app/games/$gameId"
    | "/_app/games/"
    | "/_app/teams/$teamId/manage"
    | "/_app/teams/$teamId/lists/$listId"
    | "/_app/teams/$teamId/lists/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  PrivacyRoute: typeof PrivacyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/login",
        "/privacy"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/games",
        "/_app/",
        "/_app/teams/$teamId/manage",
        "/_app/teams/$teamId/lists/$listId",
        "/_app/teams/$teamId/lists/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/_app/games": {
      "filePath": "_app.games.tsx",
      "parent": "/_app",
      "children": [
        "/_app/games/$gameId",
        "/_app/games/"
      ]
    },
    "/_app/": {
      "filePath": "_app.index.tsx",
      "parent": "/_app"
    },
    "/_app/games/$gameId": {
      "filePath": "_app.games.$gameId.tsx",
      "parent": "/_app/games"
    },
    "/_app/games/": {
      "filePath": "_app.games.index.tsx",
      "parent": "/_app/games"
    },
    "/_app/teams/$teamId/manage": {
      "filePath": "_app.teams.$teamId.manage.tsx",
      "parent": "/_app"
    },
    "/_app/teams/$teamId/lists/$listId": {
      "filePath": "_app.teams.$teamId.lists.$listId.tsx",
      "parent": "/_app"
    },
    "/_app/teams/$teamId/lists/": {
      "filePath": "_app.teams.$teamId.lists.index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
